spring:
  application:
    name: notification-service

  config:
    import: configserver:http://localhost:8888

  cloud:
    config:
      fail-fast: true

server:
  port: 0

---
spring:
  config:
    activate.on-profile: docker
    import: configserver:http://config-server:8888
