version: '3'
services:
  config-server:
    image: flow.demo.com/config-server:0.0.1-SNAPSHOT
    volumes:
      - ./configuration:/var/configuration
    environment:
      spring.cloud.config.uri: http://config-server:8888
      spring.profiles.active: native
      spring.cloud.config.server.native.searchLocations: /var/configuration
    ports:
      - 8888:8888
  broker:
    image: flow.demo.com/broker:0.0.1-SNAPSHOT
    environment:
      spring.cloud.config.uri: http://config-server:8888
    ports:
      - 7002:7002
      - 8002:8002
    depends_on:
      - config-server
  broker2:
    image: flow.demo.com/broker:0.0.1-SNAPSHOT
    environment:
      spring.profiles.active: broker2
      spring.cloud.config.uri: http://config-server:8888
    ports:
      - 7003:7003
      - 8003:8003
    depends_on:
      - config-server
  broker3:
    image: flow.demo.com/broker:0.0.1-SNAPSHOT
    environment:
      spring.profiles.active: broker3
      spring.cloud.config.uri: http://config-server:8888
    ports:
      - 7004:7004
      - 8004:8004
    depends_on:
      - config-server
  user-service:
    image: flow.demo.com/user-service:0.0.1-SNAPSHOT
    environment:
      spring.cloud.config.uri: http://config-server:8888
    depends_on:
      - config-server
    ports:
      - 8093:8093
  task-service:
    image: flow.demo.com/task-service:0.0.1-SNAPSHOT
    environment:
      spring.cloud.config.uri: http://config-server:8888
    depends_on:
      - config-server
    ports:
      - 8092:8092
  notification-service:
    image: flow.demo.com/notification-service:0.0.1-SNAPSHOT
    environment:
      spring.cloud.config.uri: http://config-server:8888
    depends_on:
      - config-server
  gateway:
    image: flow.demo.com/gateway:0.0.1-SNAPSHOT
    environment:
      spring.cloud.config.uri: http://config-server:8888
    depends_on:
      - config-server
      - task-service
      - user-service
      - notification-service
      - broker
    ports:
      - 8080:8080
