version: '3'
services:
  config-server:
    image: flow.demo.com/config-server:0.0.1-SNAPSHOT
    volumes:
      - ./configuration:/var/configuration
    environment:
      spring.profiles.active: native,docker
      spring.cloud.config.server.native.searchLocations: /var/configuration
    ports:
      - 8888:8888
  broker:
    image: flow.demo.com/broker:0.0.1-SNAPSHOT
    environment:
      spring.profiles.active: docker
      spring.config.import: configserver:http://config-server:8888
    ports:
      - 7002:7002
      - 8002:8002
    restart: on-failure
  broker2:
    image: flow.demo.com/broker:0.0.1-SNAPSHOT
    environment:
      spring.profiles.active: docker,broker2
      spring.config.import: configserver:http://config-server:8888
    ports:
      - 7003:7003
      - 8003:8003
    restart: on-failure
  broker3:
    image: flow.demo.com/broker:0.0.1-SNAPSHOT
    environment:
      spring.profiles.active: broker3,docker
      spring.config.import: configserver:http://config-server:8888
    ports:
      - 7004:7004
      - 8004:8004
    restart: on-failure
  user-service:
    image: flow.demo.com/user-service:0.0.1-SNAPSHOT
    environment:
      spring.profiles.active: docker
      spring.config.import: configserver:http://config-server:8888
    ports:
      - 8093:8093
    restart: on-failure
  task-service:
    image: flow.demo.com/task-service:0.0.1-SNAPSHOT
    environment:
      spring.profiles.active: docker
      spring.config.import: configserver:http://config-server:8888
    ports:
      - 8092:8092
    restart: on-failure
  notification-service:
    image: flow.demo.com/notification-service:0.0.1-SNAPSHOT
    environment:
      spring.profiles.active: docker
      spring.config.import: configserver:http://config-server:8888
    restart: on-failure
  gateway:
    image: flow.demo.com/gateway:0.0.1-SNAPSHOT
    environment:
      spring.profiles.active: docker
      spring.config.import: configserver:http://config-server:8888
    ports:
      - 8080:8080
    restart: on-failure
