openapi: "3.0.0"
info:
  description: "Flow Demo Gateway API"
  version: "0.0.1"
  title: "Flow Demo Gateway Service"
servers:
  - url: http://localhost:8082/
    description: "local host"
paths: {}
components:
  schemas:
    User:
      $ref: '../../../../user-service/src/main/resources/api.yaml#/components/schemas/User'
    Task:
      allOf:
        - $ref: '../../../../task-service/src/main/resources/api.yaml#/components/schemas/Task'
        - type: "object"
          properties:
            createdBy:
              $ref: '#/components/schemas/User'
    NewTaskEvent:
      $ref: '../../../../notification-service/src/main/resources/api.yaml#/components/schemas/NewTaskEvent'
    TaskDeletedEvent:
      $ref: '../../../../notification-service/src/main/resources/api.yaml#/components/schemas/TaskDeletedEvent'
    NotificationChannelEvent:
      $ref: '../../../../notification-service/src/main/resources/api.yaml#/components/schemas/NotificationChannelEvent'
    PingEvent:
      allOf:
        - $ref: '../../../../notification-service/src/main/resources/api.yaml#/components/schemas/BaseEvent'
