spring:
  application:
    name: gateway

  config:
    import: "configserver:"

  cloud:
    config:
      fail-fast: true

server:
  port: 8080

  error:
    include-message: always
    include-binding-errors: always
