openapi: "3.0.0"
info:
  description: "Task API"
  version: "0.0.1"
  title: "Task Service"
servers:
  - url: http://localhost:8082/
    description: "local host"
tags:
  - name: "Task"
    description: "Task tag"
paths:
  /tasks:
    get:
      tags:
        - "task"
      summary: "Get tasks"
      operationId: "getTasks"
      responses:
        200:
          description: "Returns list of tasks"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Task'
    post:
      tags:
        - "task"
      summary: "Create task"
      operationId: "createTask"
      requestBody:
        description: "Create task"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        201:
          description: "Task created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
  /tasks/{taskId}:
    parameters:
      - name: "taskId"
        in: "path"
        description: "get task by task id"
        required: true
        schema:
          type: "string"
          format: "uuid"
    get:
      tags:
        - "task"
      summary: "Get task"
      operationId: "getTask"
      responses:
        200:
          description: "Retrieves task by taskId"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
    delete:
      tags:
        - "task"
      summary: "Delete task"
      operationId: "deleteTask"
      parameters:
        - name: "taskId"
          in: "path"
          description: "get task by task id"
          required: true
          schema:
            type: "string"
            format: "uuid"
      responses:
        200:
          description: "Retrieves deleted task"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
components:
  schemas:
    Task:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
          example: "5adae440-5616-44c6-a3d0-f9a2398217d6"
        name:
          type: "string"
          example: "Demo"
        createdById:
          type: "string"
          format: "uuid"
          example: "5adae440-5616-44c6-a3d0-f9a2398217d6"
        tags:
          type: "array"
          items:
            $ref: '#/components/schemas/Tag'
        comments:
          type: "array"
          items:
            $ref: '#/components/schemas/Comment'
    Tag:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
          example: "5adae440-5616-44c6-a3d0-f9a2398217d6"
        value:
          type: "string"
    Comment:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
          example: "5adae440-5616-44c6-a3d0-f9a2398217d6"
        userId:
          type: "string"
          format: "uuid"
          example: "5adae440-5616-44c6-a3d0-f9a2398217d6"
        value:
          type: "string"

    NewTaskEvent:
      allOf:
        - $ref: '../../../../notification-service/src/main/resources/api.yaml#/components/schemas/UserEvent'
        - type: "object"
          properties:
            task:
              $ref: '#/components/schemas/Task'
    TaskDeletedEvent:
      allOf:
        - $ref: '../../../../notification-service/src/main/resources/api.yaml#/components/schemas/UserEvent'
        - type: "object"
          properties:
            task:
              $ref: '#/components/schemas/Task'
