application.url: localhost:8080

management:
  endpoints.web.exposure.include: "*"

  endpoint:
    restart:
      enabled: true
    health:
      show-details: always

logging:
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

spring:
  jackson:
    default-property-inclusion: NON_NULL
